{
 "title": "RHODS Usage",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  { "title": "Sandbox Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active User Signups per Cluster",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sandbox_user_accounts_current)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "User Lifecycles",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_approved_total[1d]))*60*60*24",
     "legendFormat": "Approved in the last 24h"
    },
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_deactivated_total[1d]))*60*60*24",
     "legendFormat": "Deactivated in the last 24h"
    },
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_banned_total[1d]))*60*60*24",
     "legendFormat": "Banned in the last 24h"
    },
    {
     "expr": "sum by (namespace) (rate(sandbox_user_signups_total[1d]))*60*60*24",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "All-time Users per Activations and Domain",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sandbox_users_per_activations_and_domain",
     "legendFormat": "Signups per Activations and Domain"
    }
   ]
  },
  {
   "title": "Active Users Signups per Domain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sandbox_master_user_records{domain=\"external\"})",
     "legendFormat": "External Users"
    },
    {
     "expr": "sum(sandbox_master_user_records{domain=\"internal\"})",
     "legendFormat": "Internal Users"
    }
   ]
  },
  {
   "title": "All-time User Signups per Domain",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sandbox_users_per_activations_and_domain{domain=\"external\"} or vector(0))",
     "legendFormat": "External Users"
    },
    {
     "expr": "sum(sandbox_users_per_activations_and_domain{domain=\"internal\"} or vector(0))",
     "legendFormat": "Internal Users"
    }
   ]
  },
  { "title": "RHODS Notebooks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Currently Running",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_cpu:kube_pod_container_resource_requests:sum{namespace=\"rhods-notebooks\"}"
    }
   ]
  },
  {
   "title": "RHODS Notebooks cpu (by pod stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"rhods-notebooks\"})by (pod)"
    }
   ]
  },
  {
   "title": "Running Notebooks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "namespace_cpu:kube_pod_container_resource_requests:sum{namespace=\"rhods-notebooks\"}"
    }
   ]
  },
  {
   "title": "RHODS Notebooks memory (by pod stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"\", namespace=\"rhods-notebooks\", container!=\"\", image!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Avg Usage per Day (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(sum_over_time(rate(container_cpu_usage_seconds_total{container=\"\",pod=~\"jupyterhub-nb.*\",namespace=\"rhods-notebooks\"}[5m])[1d:5m]))/sum(count_over_time(container_cpu_usage_seconds_total{container=\"\",pod=~\"jupyterhub-nb.*\",namespace=\"rhods-notebooks\"}[1d:5m]))"
    }
   ]
  }
 ]
}