# This image is just to allow the use of jq to parse the oc cli json output
FROM registry.redhat.io/openshift4/ose-cli:v4.9

RUN curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /usr/bin/jq && chmod +x /usr/bin/jq

USER 1001
